In [1]:
print("HELLO WORLD")

HELLO WORLD


In [2]:
a=10
b="HELLO"
c=True
d=10.675

In [3]:
type(a)

int

In [4]:
type(b)

str

In [5]:
a=3+10j


In [1]:
x=10
y=20
print("THE SUM IS",x+y)

THE SUM IS 30


In [5]:
a=input()
b=input()
print(a+" IS -"+b)

ALISTAIR
69
ALISTAIR IS -69


In [1]:
a="hello"

In [2]:
a.capitalize()

'Hello'

In [3]:
b=input()
if b not in a:
    print("NOT FOUND")

z
NOT FOUND


In [29]:
print("LENGTH OF",a,"IS",len(a),"BELONGING TO TYPE",type(a))

LENGTH OF hello IS 5 BELONGING TO TYPE <class 'str'>


In [37]:
for i,j in enumerate(a):
    print("ELEMENT "+str(j)+" IS AT POSITION"+str(i))

ELEMENT h IS AT POSITION0
ELEMENT e IS AT POSITION1
ELEMENT l IS AT POSITION2
ELEMENT l IS AT POSITION3
ELEMENT o IS AT POSITION4


In [41]:
print(a)

20


In [55]:
b=input()
# print(b)
b=b.strip()
print(b.replace("s","t"))
print(b.capitalize())

   shreyas labhsetwar
threyat labhtetwar
Shreyas labhsetwar


In [88]:
li=list([1,2,3,4,5])
li[4]=48

b=input()
b.split()
print(b)
for var in b:
    li.append(var)
print(li)

10
10
[1, 2, 3, 4, 48, '1', '0']


In [83]:
tup=(1,2,3)


TypeError: 'tuple' object does not support item assignment

In [112]:
set1={"10","20","30","50","40","60","80"}
set1.remove("10")
set2={"40","50","60","69"}
set3=set1.union(set2)


In [113]:
for var in set3:
    print(var)

40
80
50
30
20
69
60


In [118]:
d={"NAME" : "SHREYAS",
  "BRANCH" : "COMP",
  "ROLL" : "101730"}

In [119]:
d["NAME"]

'SHREYAS'

In [163]:
dd={
    "d1":{
        "NAME":"SHREYAS",
        "BRANCH":"COMPUTER",
    "AGE":19},
    "d2":{
        "NAME":"ALISTAIR",
        "BRANCH":"COMP",
    "HEIGHT":"169"}
    }
    


In [152]:
dd["d2"]["NAME"]


'ALISTAIR'

In [164]:
com=dd.copy()
com

{'d1': {'NAME': 'SHREYAS', 'BRANCH': 'COMPUTER', 'AGE': 19},
 'd2': {'NAME': 'ALISTAIR', 'BRANCH': 'COMP', 'HEIGHT': '169'}}

In [182]:
x=input()
for var in x:
    if int(var)%2==0:
        print(EVEN")
       
    else:
        print("ODD")


102030
ODD
EVEN
EVEN
EVEN
ODD
EVEN


In [190]:
total=0
def sum(x,y):
    return(int(x)+int(y))
    
   

In [191]:
sum(input(),input())

20
30


50

In [1]:
!pip install numpy


distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
a=[1,2,3]


In [4]:
type(a)

list

In [5]:
b=np.array([9,8,7,6,5])

In [6]:
b


array([9, 8, 7, 6, 5])

In [7]:
type(b)


numpy.ndarray

In [8]:
b.argmax()

0

In [9]:
print(b[b.argmax()])

9


In [10]:
print(b[b.argmin()])

5


In [11]:
b.max()


9

In [16]:
if b.max==b[b.argmax()]:
    print("UNIVERSAL TRUTH")
else:
    print("SORRY")

SORRY


In [25]:
b.argsort()


array([4, 3, 2, 1, 0])

In [26]:
new_a=np.array([1,2,3,4],dtype="int8")

In [27]:
b.argsort()

array([4, 3, 2, 1, 0])

In [28]:
new_a[1]=13

In [29]:
new_a

array([ 1, 13,  3,  4], dtype=int8)

In [30]:
new_a[1]=12345


In [31]:
new_a

array([ 1, 57,  3,  4], dtype=int8)

In [33]:
np.append([1,2,3],[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [34]:
new_a


array([ 1, 57,  3,  4], dtype=int8)

In [41]:
c=np.zeros((5,5))

In [42]:
c[1][2]=13

In [43]:
c


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [44]:
c[2][3]=13.131

In [45]:
c

array([[ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   , 13.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , 13.131,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])